# Server Configuration
server:
  port: 9000

# Spring Configuration
spring:
  application:
    name: poc
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/schedules}

external:
  api:
    url: ${MOCK_API_URL:http://localhost:7000/api/mock-api}
