#Server Configuration
server:
  port: 9000


#Spring Configuration
spring:
  application:
    name: poc
  data:
    mongodb:
      uri: mongodb://saastaq:SaasAdm_9808@localhost:27017/?authSource=admin
      database: schedules
      auto-index-creation: true